import { supabase } from "$lib/supabaseClient";

export async function load() {

  const { data: newlivedata } = await supabase.from('StreamData').select().eq('type','Live').order( 'actualStartTime', { ascending : true});
  const { data: newupcomingdata } = await supabase.from('StreamData').select().eq('type','Upcoming').order( 'scheduledStartTime', { ascending : true});  return {
      
      newupcoming : newupcomingdata ?? [],
      newlive : newlivedata ?? [],
    };
  }

export const config = {
    isr: {
        // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
        // Setting the value to `false` means it will never expire.
        expiration: 60,
    }
};